server.port=8081
spring.application.name=mongo-walmart

spring.mongodb.uri=mongodb+srv://cg1171803_db_user:XNNw0FP2QJraAKI4@cluster0.ijfmwo2.mongodb.net/?retryWrites=true&w=majority

spring.mongodb.database=veterinaria_mongo